INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Livros', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Eletrônicos', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Computadores', NOW());